spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AQBt55oIIoG/f+XD4V96lhQGcwTYf0ktKAm99qUkct4oWyHiyOOOWatBbPvr1mLdTRvumUhrOaW99HmSngTtWKycyoU1rHv92mTZI+D4z/rBfIq5QpdWz4aM/KdyucTs8lg05vtY9H597njwPp3TjxNeiBr5sn7vTqwYS7xiarVlhc1H1XHCcNkWutkM9si24NecM7WA9rlt8J5nKOUhJ7gRlmNGeRxQppzEEitTHLr+EfP4fZv0coXmyKeinzYJRrOS+QDpmoEQlJ6ogttIX8l+Xsun3Pvv+IHU4c1Huy19Vcj2SVPUlKgEmtiVZeIClOms0ZrMu7Z+lLavqHEOETp9P5CDZa7A1wnFlj9p28Hxy97p+1/AEroOwy3UxsZ5xZg='

token:
  expiration_time: 864000000
  secret: MlEXO3RdsNF7PyLULtK4u9eP9ljf6XDbO7UQs+/L2ATRLpR37UcLgZRIeXDiHd69+P7+m/x/xFc=
  encode-secret: TWxFWE8zUmRzTkY3UHlMVUx0SzR1OWVQOWxqZjZYRGJPN1VRcysvTDJBVFJMcFIzN1VjTGdaUkllWERpSGQ2OStQNyttL3gveEZjPQ==

gateway:
  ip: 192.168.30.166

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.